FROM python:3-slim

WORKDIR /backend

COPY requirements.txt .

RUN apt-get update \
  && apt-get -y install libpq-dev gcc \
  && pip install psycopg2 \
  && pip install -r requirements.txt


COPY . .
