FROM node:14-alpine

WORKDIR /webapp

COPY package.json .
COPY yarn.lock .

RUN yarn global add @vue/cli && \
  yarn global add serve

COPY . .

# development
CMD ["yarn", "dev"]

# production
# RUN yarn build 
# CMD ["serve -s dist"]
