name: Lint
on: [pull_request]
jobs:
  lint_webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install
        working-directory: ./webapp

      - name: Run linter
        run: yarn lint --no-fix
        working-directory: ./webapp

  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use python package Black
        uses: psf/black@stable
        with:
          src: "./backend"
