name: Code Testing
on: [pull_request]
jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python modules
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Run TDDs
        working-directory: ./backend
        run: python -m unittest integration_test
